on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Version
      #   id: version
      #   run: |
      #     if [[ $GITHUB_REF == refs/tags/* ]]; then
      #       PUSH=true
      #       VERSION="${GITHUB_REF#refs/tags/v}"
      #     else
      #       PUSH=false
      #       VERSION="0.0.0-dev"
      #     fi

      #     echo "push=$PUSH" >> $GITHUB_OUTPUT
      #     echo "version=$VERSION" >> $GITHUB_OUTPUT

      # - name: Build and push Pix Docker image to GHCR
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     context: .
      #     file: ./Dockerfile
      #     cache-from: type=gha,scope=image-ghcr
      #     cache-to: type=gha,mode=max
      #     build-args: |
      #       VERSION=${{ steps.version.outputs.version }}
      #     push: ${{ steps.version.outputs.push }}
      #     tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}

      # # ---- Pix in Pix ----

      # - name: Build docker image for Pix
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     cache-from: type=gha,scope=image-ghcr
      #     build-args: |
      #       VERSION=${{ steps.version.outputs.version }}
      #     tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
      #     load: true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Pix run Pix
        run: |
          docker buildx build --load --tag pix .
          CACHE="type=gha,scope=pix,url=$ACTIONS_CACHE_URL,token=$ACTIONS_RUNTIME_TOKEN"
          docker run --rm \
            --env PIX_DEBUG=true \
            --env PIX_DOCKER_BUILD_OPTS="--cache-from=\"$CACHE\" --cache-to=\"mode=max,$CACHE\"" \
            --volume="$PWD:$PWD" --workdir="$PWD" \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            pix run pix
