on:
  push:
    tags: ['*']
    branches: ['main']
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Version
        id: pix_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            PUSH=true
            PIX_VERSION="${GITHUB_REF#refs/tags/v}"
          else
            PUSH=false
            PIX_VERSION="0.0.0-dev"
          fi
          
          echo "push=$PUSH" >> $GITHUB_OUTPUT
          echo "version=$PIX_VERSION" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PIX_VERSION=${{ steps.pix_version.outputs.version }}
          push: ${{ steps.pix_version.outputs.push }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pix:${{ steps.pix_version.outputs.version }}
